name: release-ci

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  release:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: prepare
        id: prepare
        shell: bash
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" >> ~/.npmrc
          git config user.name "GitHub Actions Build"
          git config user.email "developers@aave.com"

      - name: install
        id: install
        run: |
          yarn install --frozen-lockfile

      - id: lint
        name: lint
        run: |
          yarn lint

      - id: test
        name: test
        run: |
          yarn test

      - id: build
        name: build
        run: |
          yarn build

      - id: prerelease
        name: prerelease
        if: |
          github.event.pull_request.head.repo.full_name == github.repository &&
          !contains(github.event.head_ref, 'dependabot') &&
          !contains(github.event.head_commit.message, 'chore(release)') &&
          github.ref != 'refs/heads/master'
        run: |
          yarn release --message "chore(release): Release v%s :tada: [ci skip]" --prerelease ${{ github.sha }}
          yarn publish --tag canary

      - id: release
        name: release
        if: |
          contains(github.event.head_commit.message, 'chore(release)') &&
          github.ref == 'refs/heads/master'
        run: |
          git tag v$(cat package.json | jq --raw-output '.version')
          git push origin v$(cat package.json | jq --raw-output '.version')
          yarn publish
